### ISSUE TITLE
Error: cp: cannot stat '/tmp/quick-cook-nixify/example/ci': No such file or directory

### ISSUE THREAD

**Issue by aleeusgr** [hughjfchen/quick-cook-or-nixify-haskell-project#1]
Hello!
Thank you for your wonderful tool. Could you please help me use it to finish my task?

## How to reproduce?
1. `cd example-validator`
2. `git clone git@github.com:hughjfchen/quick-cook-or-nixify-haskell-project.git`
3. `./quick-cook-or-nixify-haskell-project/nixify.sh . example-validator template`
4. then follow prompts on the screen and supposedly the tool will add `default.nix shell.nix release.nix docker.nix tarball.nix` to the project, then
5. `nix-build docker.nix` will create a container that can be loaded and run in docker: 
6. `docker load < result` && `docker run example-validator` 

I cloned the repo, then copied the code I have into the folder with quick-cook.
then run 
`./nixify.sh ./example example docker.nix`
 
I get reports that all is finished, but I don't see any changes in /example.

My goal is to create a  docker image to deploy Plutus code that I got from someone else.

Thank you 🙇

**Comment by hughjfchen** [comment]
@aleeusgr ,
The `nixify.sh` is to nixify an existing project which uses non-nix as the build tool. Suppose you have a haskell project located at `example` which uses `cabal` or `stack` as the build tool, with the following command:
```
<path to quick cook clone repo>/nixify.sh . example template
```
and it will generate following `nix` files under the `example` directory:

- default.nix
- shell.nix
- release.nix
- docker.nix
- tarball.nix

After that, you can run following command to build a docker image for the `example` project:
```
nix-build ./docker.nix
```

**Comment by aleeusgr** [comment]
@hughjfchen thank you for quick reply!

I still miss something: I copied quick-cook folder into my project, then run:
```
[alex@nixos:~/workshop/example-validator]$ ./quick-cook-or-nixify-haskell-project/nixify.sh . example-validator ./quick-cook-or-nixify-haskell-project/build-framework/template/docker.nix
[HOST:nixos]: - 2022-10-31 06:38:39 - INFO: - Top level - project nixifying phase - begin
[HOST:nixos]: - 2022-10-31 06:38:39 - INFO: - Top level - project env prepare phase - begin
[HOST:nixos]: - 2022-10-31 06:38:39 - INFO: - Top level - project env prepare phase - done
[HOST:nixos]: - 2022-10-31 06:38:39 - INFO: - Top level - project nixifying phase - done

[alex@nixos:~/workshop/example-validator]$ ls
app            CHANGELOG.md             quick-cook-or-nixify-haskell-project  scripts
cabal.project  example-validator.cabal  README.md                             src
```

Maybe I don't understand what is a template? 
thank you

**Comment by hughjfchen** [comment]
@aleeusgr ,
Maybe the `readme` is not very clear, when I say `template`, it means just input the word `template` as is,
so the command should be as folowing:
```
<path to quick-cook-or-nixify-haskell-project>/nixify.sh . example-validator template <-- type the word template as is here
```
It will list available templates within this reporitory and prompt you to choose one during next step.

Also, you should not copy this repository into your project, put it sibling with your project directory should be ok.

**Comment by hughjfchen** [comment]
Well, it's trying to install the `haskellPackages.rob` as `rob` is the template engine this script to use to generate the project but failed to get that package from `nixpkgs`. 

That shouldn't happen. Wait, you're in `NixOS` ? I never have a chance to test it on this platform. If you
are in `NixOS`, maybe need to change the package path to `nixos.haskellPackages.rob` I think?

**Comment by aleeusgr** [comment]
I found haskellPackage.rob [here](https://github.com/hughjfchen/quick-cook-or-nixify-haskell-project/blob/7ea021f728894fb15b366ce94f2b9095520cdc9c/project-scaffold-template/do.sh#L59)

`$nix-shell -p haskellPackages.rob`
>error: Package ‘ede-0.3.3.0’ in /nix/store/7am0kc67bbz80rvc49cn2pnxz7kcmpjc-nixos-22.05/nixos/pkgs/development/haskell-modules/hackage-packages.nix:85492 is marked as broken, refusing to evaluate.

testing with `export NIXPKGS_ALLOW_BROKEN=1`

**Comment by aleeusgr** [comment]
I've no idea. Seems like I have to go old fashioned way: follow haskell.nix tutorials until I have what I need.

Thank you.
You have a great github page, Haskell and DevOps with Nix is a very cool topic!

**Comment by hughjfchen** [comment]
@aleeusgr ,
Sorry for your bad experience. The problem is that I don't have a chance testing the script in `NixOS` platform.
I try to add some rough code to support  `NixOS`, you could update my repository and try again. 
By the way, you shouldn't put `quick-cook-or-nixify-haskell-project` under your project directory, you should move
it outside of your project directory and use the absolute path to the repository, e.g. 
```
<absolute path to the quick-cook-or-nixify-haskell-project>/nixify.sh <absolute path to the parent directory of your project> <your project directory name> template
```

**Comment by aleeusgr** [comment]
@hughjfchen 
No need to apologize, my experience is very nice actually: although I would prefer to do this step by step on my own for the sake of learning how it works, with your help I am having progress in a task I've been banging my head on for the last 3 or 4 weeks. 

I need a little bit more help, unfortunatly.

I put `example-validator` and `quick-cook` into one directory, so my call is 
`../quick-cook-or-nixify-haskell-project/nixify.sh . example-validator template`

I get:
>[HOST:nixos]: - 2022-11-02 14:30:09 - INFO: - Top level - project scaffold based on template phase - done
[HOST:nixos]: - 2022-11-02 14:30:10 - INFO: - Top level - fix up phase - begin
[HOST:nixos]: - 2022-11-02 14:30:10 - INFO: - Top level - fix up phase - done
cp: cannot stat '/tmp/quick-cook-nixify-20221102142853-pkupE0OEIu/example-validator/ci': No such file or directory

**Comment by hughjfchen** [comment]
Well, if you put `example-validator` and `quick-cook` into the same directory, I think you should call the
`nixify.sh` as following:
```
./quick-cook-or-nixify-haskell-project/nixify.sh . example-validator template
```
Remember run this command under the directory which should be the parent directory 
of both `example-validator` and `quick-cook`.

**Comment by aleeusgr** [comment]
The command you describe implies I have `quick-cook-or-nixify-haskell-project` inside `example-validator` folder.
I apologize for not being able to grasp this more quickly.

do I understand right that `.` here:
`nixify.sh . example-validator template` 
refers to the folder where `project.cabal` is?

🙇🙇🙇

**Comment by hughjfchen** [comment]
> 
> do I understand right that . here:
> nixify.sh . example-validator template
> refers to the folder where project.cabal is?

Actually, I believe `.` here should refer to the parent directory of the `example-validator`.

**Comment by aleeusgr** [comment]
oh. 
Ok, I just tried this. I have both `example-validator` and `quick-cook` in /home, 
so I called 
`./quick-cook-or-nixify-haskell-project/nixify.sh . example-validator template`
Still i get same error:
>Done: Updating all packages
[HOST:nixos]: - 2022-11-03 15:52:14 - INFO: - Top level - project scaffold based on template phase - done
[HOST:nixos]: - 2022-11-03 15:52:14 - INFO: - Top level - fix up phase - begin
[HOST:nixos]: - 2022-11-03 15:52:14 - INFO: - Top level - fix up phase - done
cp: cannot stat '/tmp/quick-cook-nixify-20221103155041-PlGXEGJ9yI/example-validator/ci': No such file or directory

**Comment by hughjfchen** [comment]
Well, that's strange. It should generate a lot of files under the tmp directory which would be copied to the target
project directory to `nixify` the project. Can you run it again and list the tmp directory to check the content when
it says `no such file or directory` ?

**Comment by aleeusgr** [comment]
Nice!! Another test to run, this brings me joy. ⚙⚙⚙

Ok, I run again and looked into /tmp, I feel silly for not thinking about it myself.
I rerun the script, and used the latest hash:
`ls /tmp/quick-cook-nixify-20221105090546-TKYMQFVo8a/example-validator/`

> api-gw  cabal.project  config  db  db-gw  env  example-validator  frontend  messaging  README.org

It seems `ci` folder does not get created.

**Comment by hughjfchen** [comment]
Ah, which template you chose when prompting? looks like you pick `full-system-nixos2111-ghc8107`. I suggest to pick `nixos2111-ghc8107-haskell.nix` instead.

**Comment by aleeusgr** [comment]
that is true.
Process completed, testing docker build

**Comment by aleeusgr** [comment]
Ok, `nix-shell` in the folder reports 
>trace: WARNING: No sha256 found for source-repository-package https://github.com/input-output-hk/plutus-apps ref=v1.0.0-alpha1 rev=(unspecified) download may fail in restricted mode (hydra)

same like what I get [here](https://github.com/input-output-hk/haskell.nix/issues/1767)

**Comment by hughjfchen** [comment]
> 
> Process completed, don't understand what's next: nix-build docker.nix reports nothing, and no result is created.
> 
Have you been waiting long enough? Nix may take a very long time to evaluate before really starting building

**Comment by aleeusgr** [comment]
oh! yes, I get empty shell prompt almost immediately.  
I found this:
>Note: Git dependencies

If you have git dependencies in your project, you'll need to [calculate sha256 hashes for them](https://input-output-hk.github.io/haskell.nix/tutorials/source-repository-hashes.html).

Reading now

**Comment by hughjfchen** [comment]
Well, that is the famous nix annoying problem. Basically, you just put an empty string for the sha256 and nix will calculate it for you and print out in the error message.

**Comment by aleeusgr** [comment]
Oh, I see.

Many thanks!
